export type Category = {
  id: string;
  name: string;
  description: string;
  color: string;
  icon: string;
  image?: string;
};

export type Question = {
  id: string;
  text: string;
  categoryId: string;
};

export const categories: Category[] = [
  {
    id: 'romance',
    name: '연애',
    description: '연인·썸 단계에서 설레거나 깊어지는 질문',
    color: 'bg-rose-500',
    icon: '💕'
  },
  {
    id: 'friends',
    name: '친구',
    description: '친구, 학교·직장 동료 등 캐주얼한 관계',
    color: 'bg-blue-500',
    icon: '👥'
  },
  {
    id: 'work',
    name: '취향',
    description: '개인적인 취향과 관심사, 좋아하는 것들에 대한 이야기',
    color: 'bg-green-500',
    icon: '💚'
  },
  {
    id: 'introduction',
    name: '자기소개',
    description: '자기 소개 및 개인적인 이야기 나누기',
    color: 'bg-purple-500',
    icon: '👋'
  },
  {
    id: 'interview',
    name: '면접준비',
    description: '랜덤 면접 예상 질문과 답변 연습하기',
    color: 'bg-indigo-500',
    icon: '🎯'
  }
];

export const questions: Question[] = [
  // 연애·썸
    { id: 'r1', text: '첫 만남에서 가장 인상 깊었던 점', categoryId: 'romance' },
    { id: 'r2', text: '처음 애인을 봤을 때 가장 먼저 든 생각', categoryId: 'romance' },
    { id: 'r3', text: '만나면서 가장 설레었던 순간', categoryId: 'romance' },
    { id: 'r4', text: '만나면서 제일 웃겼던 순간', categoryId: 'romance' },
    { id: 'r5', text: '가장 좋아하는 스킨십은?', categoryId: 'romance' },
    { id: 'r6', text: '나의 이상형은?', categoryId: 'romance' },
    { id: 'r7', text: '나를 편하게 하는 애인의 행동', categoryId: 'romance' },
    { id: 'r8', text: '애인의 장점 3가지', categoryId: 'romance' },
    { id: 'r9', text: '싸울 때 잘 푸는 방법은?', categoryId: 'romance' },
    { id: 'r10', text: '같이 가본 곳 중에서 다시 가고 싶은 장소', categoryId: 'romance' },
    { id: 'r11', text: '우리 사이에서 ‘변화’를 느낀 순간', categoryId: 'romance' },
    { id: 'r12', text: '내가 해줬던 말 중 가장 기억에 남는 한마디', categoryId: 'romance' },
    { id: 'r13', text: '나랑 하루를 바꿔 살 수 있다면 어떻게 보내고 싶어?', categoryId: 'romance' },
    { id: 'r14', text: '우리만의 약속을 하나 만든다면?', categoryId: 'romance' },
    { id: 'r15', text: '요즘 애인에게 가장 고마웠던 일', categoryId: 'romance' },
    { id: 'r16', text: '남들은 모르는 애인의 매력', categoryId: 'romance' },
    { id: 'r17', text: '우리 둘만 아는 장면 하나를 그림으로 그려줘 (직접 그리세요!)', categoryId: 'romance' },
    { id: 'r18', text: '내가 애인에게 배운 건 뭐라고 생각해?', categoryId: 'romance' },
    { id: 'r19', text: '애인을 생각하면 떠오르는 노래', categoryId: 'romance' },
    { id: 'r20', text: '함께 했던 일 중 제일 뿌듯했던 일', categoryId: 'romance' },
    { id: 'r21', text: '애인의 표정 중에 제일 좋아하는 표정', categoryId: 'romance' },
    { id: 'r22', text: '우리 둘이서만 할 수 있는 여행에 대해 설명해줘', categoryId: 'romance' },
    { id: 'r23', text: '나랑 꼭 가보고 싶은 여행지는 어디야? 가서 뭘 제일 하고 싶어?', categoryId: 'romance' },
    { id: 'r24', text: '지금 나에게 꼭 해주고 싶은 말이 있다면?', categoryId: 'romance' },
    { id: 'r25', text: '내가 없는 일주일을 상상하면 어떤 기분이 들어?', categoryId: 'romance' },
    { id: 'r26', text: '내가 너를 웃게 만든 가장 최근 순간은?', categoryId: 'romance' },
    { id: 'r27', text: '내가 잘 모르는 내 모습 하나만 알려줘.', categoryId: 'romance' },
    { id: 'r28', text: '우리의 가장 다른 점이 뭐라고 생각해?', categoryId: 'romance' },
    { id: 'r29', text: '나만의 연애 로망', categoryId: 'romance' },
    { id: 'r30', text: '나와 함께 했던 시간 중, 가장 잊기 힘든 에피소드는?', categoryId: 'romance' },
    { id: 'r31', text: '우리의 10년 뒤 미래는 어떤 모습일까?', categoryId: 'romance' },
    { id: 'r32', text: '우리를 색으로 표현한다면, 어떤 색일까?', categoryId: 'romance' },
    { id: 'r33', text: '나에게 어떤 존재이고 싶어?', categoryId: 'romance' },
    { id: 'r34', text: '나와 가장 잘 어울리는 계절', categoryId: 'romance' },
    { id: 'r35', text: '나의 가장 귀여운 버릇', categoryId: 'romance' },
    { id: 'r36', text: '나도 모르는 나만의 말버릇이 있다면?', categoryId: 'romance' },
    { id: 'r37', text: '가고 싶은 신혼여행지는?', categoryId: 'romance' },
    { id: 'r38', text: '살고 싶은 동네는?', categoryId: 'romance' },
    { id: 'r39', text: '자녀계획은?', categoryId: 'romance' },
    { id: 'r40', text: '내가 선호하는 데이트는?', categoryId: 'romance' },
    { id: 'r41', text: '내가 가장 보고싶었던 순간은?', categoryId: 'romance' },
    { id: 'r42', text: '애인의 성격중 가장 좋아하는 것은?', categoryId: 'romance' },
    { id: 'r43', text: '일주일에 몇 번 만나는게 가장 적절할까?', categoryId: 'romance' },
    { id: 'r44', text: '우리 첫키스 장소', categoryId: 'romance' },
    { id: 'r45', text: '애인이 터치 안 했으면 하는 것', categoryId: 'romance' },
    { id: 'r46', text: '내가 생각하는 바람의 기준', categoryId: 'romance' },
    { id: 'r47', text: '여사친과 어디까지 가능할까?', categoryId: 'romance' },
    { id: 'r48', text: '서로의 닮은 점', categoryId: 'romance' },
    { id: 'r49', text: '전화 vs 카톡', categoryId: 'romance' },
    { id: 'r50', text: '애인에게 궁금한 19금 질문 2가지는?', categoryId: 'romance' },
    { id: 'r51', text: '고백받았던(고백한) 날 내가 느꼈던 감정은?', categoryId: 'romance' },
    { id: 'r52', text: '애인에게 가장 감동받았던 순간은?', categoryId: 'romance' },
    { id: 'r53', text: '요즘 우리의 애정지수는?', categoryId: 'romance' },
    { id: 'r54', text: '내가 생각하는 사랑이란?', categoryId: 'romance' },
    { id: 'r55', text: '애인과 가장 찍고 싶은 커플 포즈', categoryId: 'romance' },
    { id: 'r56', text: '가장 하고 싶은 커플템', categoryId: 'romance' },
    { id: 'r57', text: '애인의 전 애인을 마주친다면?', categoryId: 'romance' },


  // 친구·동료
    { id: 'f1', text: '가장 기억에 남는 친구와의 추억은?', categoryId: 'friends' },
    { id: 'f2', text: '우리가 제일 많이 웃었던 순간은?', categoryId: 'friends' },
    { id: 'f3', text: '친구가 했던 말이나 행동 중 의외였던 건?', categoryId: 'friends' },
    { id: 'f4', text: '같이 했던 일 중 제일 재밌었던 일', categoryId: 'friends' },
    { id: 'f5', text: '친구가 해준 것 중에 가장 고마웠던 건?', categoryId: 'friends' },
    { id: 'f6', text: '우리의 닮은 점 세 가지', categoryId: 'friends' },
    { id: 'f7', text: '같이 가보고 싶은 곳이 있다면?', categoryId: 'friends' },
    { id: 'f8', text: '내가 모르는 내 장점이 있다면?', categoryId: 'friends' },
    { id: 'f9', text: '친구와 있었을 때 가장 편했던 순간은 언제야?', categoryId: 'friends' },
    { id: 'f10', text: '우리가 서로 도전해봤으면 하는 것', categoryId: 'friends' },
    { id: 'f11', text: '우리의 친해진 계기', categoryId: 'friends' },
    { id: 'f12', text: '우리 사이가 달라졌다고 느꼈던 순간', categoryId: 'friends' },
    { id: 'f13', text: '친구가 나에게 전염시킨 습관', categoryId: 'friends' },
    { id: 'f14', text: '친구가 없으면 아쉬운 순간', categoryId: 'friends' },
    { id: 'f15', text: '함께 보냈던 하루 중 다시 돌아가고 싶은 하루', categoryId: 'friends' },
    { id: 'f16', text: '나눴던 대화 중 오래 기억에 남는 건?', categoryId: 'friends' },
    { id: 'f17', text: '오늘 갑자기 1억 받으면 제일 먼저 살 것 같은 건?', categoryId: 'friends' },
    { id: 'f18', text: '내가 술 마시면 제일 먼저 할 것 같은 짓', categoryId: 'friends' },
    { id: 'f19', text: '친구가 SNS에 절대 올릴 것 같지 않은 사진', categoryId: 'friends' },
    { id: 'f20', text: '서로 닮았다고 하면 기분 나쁠 것 같은 동물은?', categoryId: 'friends' },
    { id: 'f21', text: '우리가 영화 찍는다면 장르는? 그리고 우리의 역할은?', categoryId: 'friends' },
    { id: 'f22', text: '친구와 하루를 바꾼다면 하고 싶은 장난은?', categoryId: 'friends' },
    { id: 'f23', text: '서로 별명 하나씩 붙여주기', categoryId: 'friends' },
    { id: 'f24', text: '서로에게 ‘의외로 잘 어울릴거 같은 패션’ 추천하기', categoryId: 'friends' },
    { id: 'f25', text: '친구가 회사나 학교에서 몰래 하는 짓은?', categoryId: 'friends' },
    { id: 'f26', text: '서로 휴대폰 앨범 맨 마지막 사진 공개 가능 vs 불가능', categoryId: 'friends' },
    { id: 'f27', text: '친구들끼리 할 수 있는 단체 사진 포즈 만들기', categoryId: 'friends' },
    { id: 'f28', text: '내가 갑자기 방송에 나오면 무슨 이유일까?', categoryId: 'friends' },
    { id: 'f29', text: '같이 살면 생길 법한 웃긴 사건이 있다면?', categoryId: 'friends' },
    { id: 'f30', text: '서로의 웃음소리를 따라 해보기', categoryId: 'friends' },
    { id: 'f31', text: '나랑 안 어울리는 직업이 있다면?', categoryId: 'friends' },
    { id: 'f32', text: '내가 갑자기 유명인 되면 무슨 분야일까?', categoryId: 'friends' },
    { id: 'f33', text: '내가 장난으로라도 못 할 것 같은 행동은?', categoryId: 'friends' },
    { id: 'f34', text: '나랑 둘이서 유튜브 채널하면 주제는?', categoryId: 'friends' },
    { id: 'f35', text: '서로에게 맞는 노래 한 소절 불러주기', categoryId: 'friends' },
    { id: 'f36', text: '내가 갑자기 길거리에서 주목받을 이유는?', categoryId: 'friends' },
    { id: 'f37', text: '내가 갑자기 외계인을 만나면 제일 먼저 할 말은?', categoryId: 'friends' },
    { id: 'f38', text: '제일 좋아하는 음료 맞추기', categoryId: 'friends' },
    { id: 'f39', text: '처음 만났을 때, 서로의 첫인상은?', categoryId: 'friends' },
    { id: 'f40', text: '서로 싫어하는 음식 맞추기', categoryId: 'friends' },
    { id: 'f41', text: '나랑 닮은 캐릭터가 있다면?', categoryId: 'friends' },

  // 취향·관심사
  { id: 'w1', text: '가장 좋아하는 음악 장르?', categoryId: 'work' },
  { id: 'w2', text: '언젠가 죽게 된다면 나의 묘비명은?', categoryId: 'work' },
  { id: 'w3', text: '하루 중 내가 가장 많이 하는 말', categoryId: 'work' },
  { id: 'w4', text: '내가 가장 행복할 때 하는 것?', categoryId: 'work' },
  { id: 'w5', text: '내가 가장 슬플 때 하는 것', categoryId: 'work' },
  { id: 'w6', text: '나만의 스트레스 해소 방법은?', categoryId: 'work' },
  { id: 'w7', text: '내가 가장 스트레스 받을 때 하는 말', categoryId: 'work' },
  { id: 'w8', text: '내가 아는 나만의 단점', categoryId: 'work' },
  { id: 'w9', text: '먹으면 바로 행복해지는 음식', categoryId: 'work' },
  { id: 'w10', text: '죽기 전에 꼭 가보고 싶은 나라', categoryId: 'work' },
  { id: 'w11', text: '인생에서 가장 기억에 남는 여행은? 그 여행에서 가장 기억에 남는 순간은?', categoryId: 'work' },
  { id: 'w12', text: '좋아하는 연예인', categoryId: 'work' },
  { id: 'w13', text: '가장 존경하는 사람', categoryId: 'work' },
  { id: 'w14', text: '인생 드라마 TOP 3', categoryId: 'work' },
  { id: 'w15', text: '인생 책 TOP 3', categoryId: 'work' },
  { id: 'w16', text: '인생 영화 TOP 3', categoryId: 'work' },
  { id: 'w17', text: '좋아하는 글귀는?', categoryId: 'work' },
  { id: 'w18', text: '가장 좋아하는 과자', categoryId: 'work' },
  { id: 'w19', text: '가장 싫어하는 과자', categoryId: 'work' },
  { id: 'w20', text: '가장 좋아하는 음식', categoryId: 'work' },
  { id: 'w21', text: '가장 싫어하는 음식', categoryId: 'work' },
  { id: 'w22', text: '주위에 꼭 추천하고 싶은 것', categoryId: 'work' },
  { id: 'w23', text: '내가 가장 좋아하는 계절', categoryId: 'work' },
  { id: 'w24', text: '내가 가장 싫어하는 계절', categoryId: 'work' },
  { id: 'w25', text: '갖고 싶은 초능력', categoryId: 'work' },
  { id: 'w26', text: '가장 좋아하는 요일', categoryId: 'work' },
  { id: 'w27', text: '가장 좋아하는 동물', categoryId: 'work' },
  { id: 'w28', text: '좋아하는 스포츠는?', categoryId: 'work' },
  { id: 'w29', text: '혼자 해본 것 중 가장 좋았던 것?', categoryId: 'work' },
  { id: 'w30', text: '나만의 손절 기준', categoryId: 'work' },
  { id: 'w31', text: '좋아하는 애니메이션', categoryId: 'work' },
  { id: 'w32', text: '익숙한 것 vs 새로운 도전', categoryId: 'work' },
  { id: 'w33', text: '말하기 vs 글쓰기', categoryId: 'work' },
  { id: 'w34', text: '가장 연락 많이 하는 사람', categoryId: 'work' },
  { id: 'w35', text: '하루 중 가장 좋아하는 시간대', categoryId: 'work' },
  { id: 'w36', text: '좋아하는 것과 잘하는 것 3가지씩 답변', categoryId: 'work' },
  { id: 'w37', text: '가장 오래된 나의 물건은?', categoryId: 'work' },
  { id: 'w38', text: '좋아하는 과일', categoryId: 'work' },
  { id: 'w39', text: '좋아하는 반찬', categoryId: 'work' },
  { id: 'w40', text: '좋아하는 라면', categoryId: 'work' },
  { id: 'w41', text: '가장 좋아하는 베라 맛', categoryId: 'work' },
  { id: 'w42', text: '가장 좋아하는 치킨', categoryId: 'work' },
  { id: 'w43', text: '죽기 전에 꼭 먹어보고 싶은 음식', categoryId: 'work' },

  // 자기소개
  { id: 'i1', text: '3줄 요약 자기소개하기!', categoryId: 'introduction' },
  { id: 'i2', text: '하루를 시작할 때 꼭 하는 루틴', categoryId: 'introduction' },
  { id: 'i3', text: '본인은 흡연자/비흡연자?', categoryId: 'introduction' },
  { id: 'i4', text: '자신의 전공과 그 전공을 선택한 이유는?', categoryId: 'introduction' },
  { id: 'i5', text: '여행에서 꼭 모으는 기념품이 있다면?', categoryId: 'introduction' },
  { id: 'i6', text: '어릴 때 꿈꾸던 직업은? 지금은 달라졌는지?', categoryId: 'introduction' },
  { id: 'i7', text: '인생에서 꼭 이루고 싶은 목표 한 가지를 꼽는다면?', categoryId: 'introduction' },
  { id: 'i8', text: '나만의 버킷리스트 3가지가 있다면?', categoryId: 'introduction' },
  { id: 'i9', text: '최근에 본 영화나 드라마 중 가장 좋았던 건?', categoryId: 'introduction' },
  { id: 'i10', text: '자주 가는 맛집이나 카페', categoryId: 'introduction' },
  { id: 'i11', text: '스트레스 받을 때 제일 먼저 하는 행동', categoryId: 'introduction' },
  { id: 'i12', text: '평생 한 가지만 먹을 수 있다면?', categoryId: 'introduction' },
  { id: 'i13', text: '최근에 새로 시작한 취미나 관심사', categoryId: 'introduction' },
  { id: 'i14', text: '사람들이 잘 모르는 너의 장점', categoryId: 'introduction' },
  { id: 'i15', text: '나의 MBTI와 그 성격 유형에 대해 간단하게 설명', categoryId: 'introduction' },
  { id: 'i16', text: '여행 갈 때 도시vs 자연', categoryId: 'introduction' },
  { id: 'i17', text: '지금 당장 1주일 휴가가 주어진다면?', categoryId: 'introduction' },
  { id: 'i18', text: '어릴 때 자주 하던 놀이나 게임', categoryId: 'introduction' },
  { id: 'i19', text: '올해 안에 꼭 해보고 싶은 일', categoryId: 'introduction' },
  { id: 'i20', text: '자신을 한 단어로 표현한다면?', categoryId: 'introduction' },
  { id: 'i21', text: '지금까지 살면서 가장 용기냈던 순간', categoryId: 'introduction' },
  { id: 'i22', text: '인생에서 가장 힘들었던 순간을 극복한 방법은?', categoryId: 'introduction' },
  { id: 'i23', text: '자신만의 인생 모토는?', categoryId: 'introduction' },
  { id: 'i24', text: '휴일에 어떤걸 하면서 재충전해?', categoryId: 'introduction' },
  { id: 'i25', text: '최근에 도전해보고 싶은 운동이나 활동이 있다면?', categoryId: 'introduction' },
  { id: 'i26', text: '좋아하는 계절과 그 이유는?', categoryId: 'introduction' },
  { id: 'i27', text: '어린 시절 가장 자주 먹던 간식이나 음식은?', categoryId: 'introduction' },
  { id: 'i28', text: '여행 가서 꼭 하는 루틴이 있다면?', categoryId: 'introduction' },
  { id: 'i29', text: '자기만의 징크스가 있다면?', categoryId: 'introduction' },
  { id: 'i30', text: '인생에서 가장 크게 웃었던 순간', categoryId: 'introduction' },
  { id: 'i31', text: '책, 영화, 노래 중 하나만 평생 선택해야 한다면?', categoryId: 'introduction' },
  { id: 'i32', text: '평소에 가장 많이 쓰는 앱은?', categoryId: 'introduction' },
  { id: 'i33', text: '내가 닮았다고 생각하는 인물(현실/가상)은?', categoryId: 'introduction' },
  { id: 'i34', text: '최근에 ‘이건 꼭 다시 하고 싶다’ 느꼈던 경험이 있다면?', categoryId: 'introduction' },
  { id: 'i35', text: '인생에서 가장 기억에 남는 선물', categoryId: 'introduction' },
  { id: 'i36', text: '혼자 있는 시간이 주어졌을 때 가장 하고 싶은 건?', categoryId: 'introduction' },
  { id: 'i37', text: '살면서 꼭 만나고 싶은 사람', categoryId: 'introduction' },
  { id: 'i38', text: '좋아하는 패션 스타일이나 색깔', categoryId: 'introduction' },
  { id: 'i39', text: '친구들이 말하는 자신의 첫인상', categoryId: 'introduction' },
  { id: 'i40', text: '예전에는 싫었는데 지금은 좋아진 게 있다면?', categoryId: 'introduction' },
  { id: 'i41', text: '앞으로 10년 뒤의 나는 어떤 모습일까?', categoryId: 'introduction' },
  { id: 'i42', text: '올해를 한 문장으로 표현한다면?', categoryId: 'introduction' },
  { id: 'i43', text: '평생 꼭 지키고 싶은 가치나 원칙은?', categoryId: 'introduction' },
  { id: 'i44', text: '요즘 가장 기다리고 있는 일', categoryId: 'introduction' },
  { id: 'i45', text: '내 인생을 책으로 쓴다면, 첫 문장은?', categoryId: 'introduction' },
  { id: 'i46', text: '들어봤던 말 중에 가장 무서웠던 얘기는?', categoryId: 'introduction' },
  { id: 'i47', text: '지니가 소원 3가지를 이뤄준다면 빌고 싶은 소원은?', categoryId: 'introduction' },
  { id: 'i48', text: '자신의 이름 한자와 뜻', categoryId: 'introduction' },
  { id: 'i49', text: '자신의 키', categoryId: 'introduction' },
  { id: 'i50', text: '자신과 친해지는 법 3가지', categoryId: 'introduction' },
  { id: 'i51', text: '즐겨보는 유튜버 3명', categoryId: 'introduction' },
  { id: 'i52', text: '자신의 취미', categoryId: 'introduction' },
  { id: 'i53', text: '마지막 연애가 언제였는지?', categoryId: 'introduction' },
  { id: 'i54', text: '내가 가진 것 중 가장 비싼 것', categoryId: 'introduction' },
  { id: 'i55', text: '내가 생각하는 매력적인 사람', categoryId: 'introduction' },
  { id: 'i56', text: '언젠가 도전해보고 싶은 직업', categoryId: 'introduction' },
  { id: 'i57', text: '내가 가장 고치고 싶은 습관', categoryId: 'introduction' },

  // 면접준비
  { id: 'int1', text: '자신의 강점은 무엇인가요?', categoryId: 'interview' },
  { id: 'int2', text: '본인에 대해 간단히 소개해 주세요. (30초)', categoryId: 'interview' },
  { id: 'int3', text: '본인에 대해 간단히 소개해 주세요. (1분)', categoryId: 'interview' },
  { id: 'int4', text: '이번 직무에 지원하게 된 이유는 무엇인가요?', categoryId: 'interview' },
  { id: 'int5', text: '우리 회사를 선택한 가장 큰 이유는 무엇인가요?', categoryId: 'interview' },
  { id: 'int6', text: '다른 회사가 아닌 우리 회사여야 하는 이유는요?', categoryId: 'interview' },
  { id: 'int7', text: '본인의 장점과 단점을 한 가지씩 말해주세요.', categoryId: 'interview' },
  { id: 'int8', text: '주위 사람들이 본인을 어떻게 평가하나요?', categoryId: 'interview' },
  { id: 'int9', text: '본인이 가장 자신 있는 역량은 무엇인가요?', categoryId: 'interview' },
  { id: 'int10', text: '지금까지 살아오면서 가장 성취감을 느낀 경험은?', categoryId: 'interview' },
  { id: 'int11', text: '실패 경험이 있다면, 어떻게 극복했는지 말씀해주세요.', categoryId: 'interview' },
  { id: 'int12', text: '앞으로 5년 뒤, 어떤 모습이 되고 싶은가요?', categoryId: 'interview' },
  { id: 'int13', text: '해당 직무를 수행하기 위해 필요한 역량은 무엇이라고 생각하나요?', categoryId: 'interview' },
  { id: 'int14', text: '전공(또는 이전 경험)이 이번 직무에 어떤 도움이 된다고 생각하나요?', categoryId: 'interview' },
  { id: 'int15', text: '관련 프로젝트나 경험이 있다면 구체적으로 말씀해주세요.', categoryId: 'interview' },
  { id: 'int16', text: '새로운 업무를 빠르게 익히기 위해 어떤 방법을 쓰시나요?', categoryId: 'interview' },
  { id: 'int17', text: '협업 과정에서 본인이 맡았던 역할과 기여도를 설명해주세요.', categoryId: 'interview' },
  { id: 'int18', text: '시간 압박 속에서 업무를 처리했던 경험이 있나요?', categoryId: 'interview' },
  { id: 'int19', text: '업무 중 우선순위를 어떻게 정하나요?', categoryId: 'interview' },
  { id: 'int20', text: '문제 상황이 발생했을 때 해결한 경험을 말해주세요.', categoryId: 'interview' },
  { id: 'int21', text: '이 직무에서 본인의 강점을 어떻게 발휘할 계획인가요?', categoryId: 'interview' },
  { id: 'int22', text: '직무와 관련해 최근에 공부하거나 준비한 것은 무엇인가요?', categoryId: 'interview' },
  { id: 'int23', text: '직장 생활에서 가장 중요하다고 생각하는 가치는 무엇인가요?', categoryId: 'interview' },
  { id: 'int24', text: '갈등이 발생했을 때 어떻게 대처하나요?', categoryId: 'interview' },
  { id: 'int25', text: '팀원과 의견이 다를 때 어떻게 조율하나요?', categoryId: 'interview' },
  { id: 'int26', text: '리더 역할과 팔로워 역할 중 어떤 것이 더 편한가요?', categoryId: 'interview' },
  { id: 'int27', text: '본인의 성격이 업무에 어떤 영향을 준다고 생각하나요?', categoryId: 'interview' },
  { id: 'int28', text: '동료에게 인정받았던 경험이 있다면 말씀해주세요.', categoryId: 'interview' },
  { id: 'int29', text: '직장 내에서 가장 중요하게 지켜야 할 매너는?', categoryId: 'interview' },
  { id: 'int30', text: '본인과 성향이 다른 사람과 일한 경험은?', categoryId: 'interview' },
  { id: 'int31', text: '회사에서 배우고 싶은 점은 무엇인가요?', categoryId: 'interview' },
  { id: 'int32', text: '상사가 잘못된 지시를 내렸을 때 어떻게 하시겠습니까?', categoryId: 'interview' },
  { id: 'int33', text: '야근이 잦은데 괜찮으신가요?', categoryId: 'interview' },
  { id: 'int34', text: '업무 능력이 떨어지는 동료와 함께 해야 한다면?', categoryId: 'interview' },
  { id: 'int35', text: '급하게 처리해야 할 업무와 중요한 업무가 겹친다면?', categoryId: 'interview' },
  { id: 'int36', text: '업무 실수로 큰 문제가 생겼을 때 대처 방법은?', categoryId: 'interview' },
  { id: 'int37', text: '성과가 나지 않는 프로젝트에 계속 참여해야 한다면?', categoryId: 'interview' },
  { id: 'int38', text: '자신의 의견이 무시당했을 때 어떻게 행동하시나요?', categoryId: 'interview' },
  { id: 'int39', text: '우리 회사에 입사하지 못한다면 어떤 계획이 있나요?', categoryId: 'interview' },
  { id: 'int40', text: '월급이 적어도 이 회사에 다닐 이유가 있나요?', categoryId: 'interview' },
  { id: 'int41', text: '경쟁사에서 더 높은 연봉으로 스카우트 제안이 온다면 어떻게 하시겠습니까?', categoryId: 'interview' },
  { id: 'int42', text: '업계의 최근 동향을 아시나요?', categoryId: 'interview' },
  { id: 'int43', text: '해당 업계에서 앞으로 중요해질 트렌드는 무엇이라고 생각하나요?', categoryId: 'interview' },
  { id: 'int44', text: '경쟁사와 비교했을 때 우리 회사만의 차별점은?', categoryId: 'interview' },
  { id: 'int45', text: '직무를 수행하는 데 필요한 최신 기술·지식은 무엇인가요?', categoryId: 'interview' },
  { id: 'int46', text: '우리 회사 제품/서비스를 사용해 본 적이 있나요? 장단점을 1가지씩 말해주세요.', categoryId: 'interview' },
  { id: 'int47', text: '회사의 최근 뉴스나 이슈 중 기억에 남는 것은?', categoryId: 'interview' },
  { id: 'int48', text: '입사 후 가장 먼저 배우고 싶은 것은 무엇인가요?', categoryId: 'interview' },
  { id: 'int49', text: '해당 업계의 가장 큰 도전과제는 무엇이라고 생각하나요?', categoryId: 'interview' },
  { id: 'int50', text: '입사 후 첫 3개월 동안 어떤 목표를 세우고 일하고 싶나요?', categoryId: 'interview' },
  { id: 'int51', text: '본인이 실패했다고 느끼는 경험을 하나 이야기하고, 거기서 얻은 교훈은 무엇인가요?', categoryId: 'interview' },
  { id: 'int52', text: '지금의 가치관을 형성한 결정적인 사건은 무엇인가요?', categoryId: 'interview' },
  { id: 'int53', text: '당신을 가장 크게 성장시킨 피드백은 무엇이었나요?', categoryId: 'interview' },
  { id: 'int54', text: '완벽하게 준비한 일이 예상과 다르게 흘러갔을 때, 어떻게 대처했나요?', categoryId: 'interview' },
  { id: 'int55', text: '지금까지 살면서 가장 큰 결정을 내렸던 순간은 언제였나요?', categoryId: 'interview' },
  { id: 'int56', text: '힘든 상황에서 스스로 동기를 유지하는 방법은 무엇인가요?', categoryId: 'interview' },
  { id: 'int57', text: '‘이 정도면 충분하다’와 ‘더 나아가야 한다’의 기준은 어떻게 구분하나요?', categoryId: 'interview' },
  { id: 'int58', text: '본인이 이 직무에 적합하지 않을 수도 있다고 생각하는 이유는?', categoryId: 'interview' },
  { id: 'int59', text: '원했던 직무와 다른 직무, 부서에 배정받게 된다면 어떻게 하실건가요?', categoryId: 'interview' },
  { id: 'int60', text: '다른 사람이 당신을 오해했을 때, 어떻게 풀어나갔나요?', categoryId: 'interview' },
  { id: 'int61', text: '타인의 조언을 받아들인 경험과 그렇지 않은 경험의 차이를 이야기해주세요.', categoryId: 'interview' },
  { id: 'int62', text: '당신이 팀에 부정적인 영향을 준 적이 있다면, 어떻게 회복했나요?', categoryId: 'interview' },
  { id: 'int63', text: '지금 이 자리에서 스스로 가장 부족하다고 느끼는 점은 무엇인가요?', categoryId: 'interview' },
  { id: 'int64', text: '장기적으로 이루고 싶은 인생 목표와, 그 목표가 이 직무와 어떤 관련이 있나요?', categoryId: 'interview' },
  { id: 'int65', text: '본인에게 ‘성공’이란 어떤 의미인가요?', categoryId: 'interview' },
  { id: 'int66', text: '가장 존경하는 인물은 누구이며, 그 이유는 무엇인가요?', categoryId: 'interview' },
  { id: 'int67', text: '이 직무에서 실패할 경우, 그 이유는 무엇일 것 같나요?', categoryId: 'interview' },
  { id: 'int68', text: '10년 후의 나에게 지금 꼭 해주고 싶은 말은 무엇인가요?', categoryId: 'interview' },
  { id: 'int69', text: '당신의 경력에서 ‘전환점’이 될 수 있었던 기회를 놓친 적이 있나요? 그 이유는?', categoryId: 'interview' }
];